version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend